version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:


  block-dev-to-main:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Block Dev to Main
          command: |
            echo "Source branch: $CIRCLE_PR_BRANCH"
            echo "Target branch: $CIRCLE_BRANCH"

            if [ -z "$CIRCLE_PR_BRANCH" ]; then
              echo "Pas de PR détectée, skip"
              exit 0
            fi

            if [ "$CIRCLE_BRANCH" = "main" ]; then
              if [ "$CIRCLE_PR_BRANCH" = "dev" ] || \
                echo "$CIRCLE_PR_BRANCH" | grep -qE '^(feature|fix)/'; then
                echo "Merge de $CIRCLE_PR_BRANCH vers main interdit !"
                exit 1
              fi
            fi

            echo "OK"

  test-api:
    docker:
      - image: cimg/node:22.12
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build API
          command: npx turbo run build --filter=@student-life/api
      - run:
          name: Tests API
          command: npx turbo run test --filter=@student-life/api

  test-web:
    docker:
      - image: cimg/node:22.12
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Web
          command: npx turbo run build --filter=@student-life/web
      - run:
          name: Tests Web
          command: npx turbo run test --filter=@student-life/web

  test-mobile:
    docker:
      - image: cimg/node:22.12
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Tests Mobile
          command: npx turbo run test --filter=@student-life/mobile

workflows:
  ci:
    jobs:
      - block-dev-to-main:
        filters:
          branches:
            only: main
      - test-api
      - test-web
      - test-mobile